version: '3.8'

services:
  php-sample:
    container_name: 'php'
    build:
      context: ./
      dockerfile: Dockerfile
    volumes: 
      - ./www/html:/var/www/html/
    ports:
      - 8181:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
  db:
    container_name: db
    image: mysql
    restart: always
    volumes:
      - ./db:/db-entrypoint/
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MY_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - 3099:3306
